coder_task:
  description: >
    Write efficient Python code to answer the query: {topic}.
    Ensure the code stores the final answer in a variable called `result`.
  expected_output: >
    Python code that is well-structured, optimized, and stores the final answer in `result`.
  agent: coder

executor_task:
  description: >
    Execute the provided python code snippets, ensuring they run correctly.
    Validate the output and catch any errors that may arise during execution.
  expected_output: >
    The output of the executed code (answer to {topic}) or error messages if any issues were encountered.
  agent: executor

reporting_task:
  description: >
    Summarize the full process: the generated code, the execution result,
    and provide insights or recommendations.
  expected_output: >
    A clear report that includes the original query ({topic}), the code logic, the execution result and key insights and recommendations.
  agent: reporting_analyst
