research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find relevant information given.
    Include current statistics, trends, key developments, challenges, and opportunities.
    The current year is {current_year}.
  expected_output: >
    A collection of all relevant and useful information about {topic}.
    Include detailed findings, statistics, trends, recent developments, and any useful data.
    Present the information in a structured format with clear sections and detailed explanations.
  agent: researcher

summarize_task:
  description: >
    Take the research findings and create a concise summary.
    Focus on the most important points and key insights about {topic}.
  expected_output: >
    A clear summary with main points organized in 3-4 key categories
  agent: summarizer

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report contains any and all relevant information.
  expected_output: >
    A report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  markdown: true
  output_file: report.md
